# ~/.config/paru/paru.conf

[options]
# UI & Interaction
BottomUp
SudoLoop
NewsOnUpgrade

# Maintenance
CleanAfter
# RemoveMake

# Updates
UpgradeMenu
CombinedUpgrade

SkipReview

# Devel options (optional, uncomment if you use -git packages)
# Devel
# DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg -fossil
# PgpFetch
